/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */
import type { Config } from "@puckeditor/core";
import { mainConfig, type MainConfigProps } from "@yext/visual-editor";
import { ProofSection as FitnessProofTemplateComponentProofSection } from "./components/ProofSection";
type GeneratedFitnessProofTemplateConfigProps = Pick<MainConfigProps, "MainContent"> & {
  "ProofSection": any;
};
export const FitnessProofTemplateConfig: Config<GeneratedFitnessProofTemplateConfigProps> = {
  components: {
    "MainContent": mainConfig.components.MainContent,
    "ProofSection": FitnessProofTemplateComponentProofSection,
  },
  categories: {
  "structure": {
    "components": [
      "MainContent"
    ],
    "visible": false,
    "title": "Structure"
  },
  "components": {
    "title": "Components",
    "components": [
      "ProofSection"
    ]
  },
  "other": {
    "title": "Other",
    "visible": false,
    "components": []
  }
},
};