buildConfiguration:
  buildCommand: npm run build -- ${YEXT_REVERSE_PROXY_PREFIX:+--reverse-proxy-prefix="$YEXT_REVERSE_PROXY_PREFIX"} --pluginTotalFilesizeLimit 15
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
      - .yextrc
      - sites-config/features.json
livePreviewConfiguration:
  serveCommand: "npm run dev -- --port 8080 --universe $YEXT_UNIVERSE --account $YEXT_ACCOUNT_ID"
  setupCommand: ":"
siteStream:
  id: site-stream
  entityId: site
  fields:
  - name
  localization:
   locales:
   - en
sitemap:
  excludeList:
    - edit