buildConfiguration:
  buildCommand: npm run build -- ${YEXT_REVERSE_PROXY_PREFIX:+--reverse-proxy-prefix="$YEXT_REVERSE_PROXY_PREFIX"}
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  serveCommand: "npm run dev -- --port 8080"
  setupCommand: ":"
siteStream:
  id: site-stream
  entityId: site
  fields:
  - name
  localization:
   locales:
   - en
sitemap:
  excludeList:
    - edit
