/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */
import "@yext/visual-editor/editor.css";
import "../index.css";
import {
  type GetHeadConfig,
  type GetPath,
  type HeadConfig,
  type TemplateConfig,
  type TemplateProps,
  type TemplateRenderProps,
} from "@yext/pages";
import {
  applyTheme,
  defaultThemeConfig,
  Editor,
  type MigrationRegistry,
  usePlatformBridgeDocument,
  usePlatformBridgeEntityFields,
} from "@yext/visual-editor";
import { SectionLibraryVisualEditorProvider } from "@yext/visual-editor/section-library-support";
import tailwindConfig from "../../tailwind.config";
import { translationLoaders } from "../library/.generated/i18n";

const sectionLibraryMigrationRegistry: MigrationRegistry = [];

const editorPath = "edit/mission-entity-layout/local";
const editorName = "edit-mission-entity-layout";
const componentRegistry = {  "mission-entity-layout": () => import("../library/.generated/libraryConfig-mission-entity-layout").then(({ sectionLibraryConfig }) => sectionLibraryConfig),};

export const getPath: GetPath<TemplateProps> = () => editorPath;
export const config: TemplateConfig = { name: editorName };
export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  document,
}): HeadConfig => ({
  title: editorName,
  other: applyTheme(document, "./", defaultThemeConfig),
});

const Edit = (): JSX.Element => {
  const document = usePlatformBridgeDocument();
  const entityFields = usePlatformBridgeEntityFields();
  return (
    <SectionLibraryVisualEditorProvider
      templateProps={{ document }}
      entityFields={entityFields}
      tailwindConfig={tailwindConfig}
      translationLoaders={translationLoaders}
    >
      <Editor
        document={document}
        componentRegistry={componentRegistry}
        themeConfig={defaultThemeConfig}
        sectionLibraryMigrationRegistry={sectionLibraryMigrationRegistry}
      />
    </SectionLibraryVisualEditorProvider>
  );
};

export default Edit;
