/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/editor.css";
import "../index.css";
import {
  GetPath,
  Template,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
import { type Config } from "@puckeditor/core";
import {
  defaultThemeConfig,
  LocalEditorShell,
  type MigrationRegistry,
} from "@yext/visual-editor";
import tailwindConfig from "../../tailwind.config";
import { translationLoaders } from "../library/.generated/i18n";
import { sectionLibraryConfig as LayoutConfig0 } from "../library/.generated/libraryConfig-mission-entity-layout";
import { sectionLibraryConfig as LayoutConfig1 } from "../library/.generated/libraryConfig-mission-section-library-directory";
import { sectionLibraryConfig as LayoutConfig2 } from "../library/.generated/libraryConfig-mission-section-library-locator";
const sectionLibraryMigrationRegistry: MigrationRegistry = [];

const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
const localEditorStylesheetHrefs: string[] = [];
const componentRegistry: Record<string, Config<any>> = {
    "mission-entity-layout": LayoutConfig0,
  "mission-section-library-directory": LayoutConfig1,
  "mission-section-library-locator": LayoutConfig2,
};

export const getPath: GetPath<TemplateProps> = () => {
  return DEFAULT_LOCAL_EDITOR_ROUTE.slice(1);
};

export const config: TemplateConfig = {
  name: "local-editor",
};

export const getHeadConfig: GetHeadConfig<
  TemplateRenderProps
> = (): HeadConfig => {
  const stylesheetLinks = localEditorStylesheetHrefs.map((href) => {
    return `<link href="${href}" rel="stylesheet" data-visual-editor-font="true">`;
  });

  return {
    title: "Local Editor",
    ...(stylesheetLinks.length > 0
      ? {
          other: stylesheetLinks.join("\n"),
        }
      : {}),
  };
};

const LocalEditor: Template<TemplateRenderProps> = () => {
  return (
    <LocalEditorShell
      apiBasePath="/__yext_visual_editor/local-editor"
      routePath={DEFAULT_LOCAL_EDITOR_ROUTE}
      componentRegistry={componentRegistry}
      tailwindConfig={tailwindConfig}
      themeConfig={defaultThemeConfig}
      sectionLibraryMigrationRegistry={sectionLibraryMigrationRegistry}
      translationLoaders={translationLoaders}
    />
  );
};

export default LocalEditor;
