import React from "react";
import { PuckComponent } from "@puckeditor/core";
import {
  resolveComponentData,
  TranslatableString,
  useDocument,
  YextComponentConfig,
  YextEntityField,
  YextFields,
} from "@yext/visual-editor";
import { useTranslation } from "react-i18next";

export type ProofSectionProps = {
  text: YextEntityField<TranslatableString>;
  textAlignment: "left" | "center" | "right";
  backgroundColorChoice: "primary" | "dark" | "light";
  textColorChoice: "dark" | "light" | "text" | "mutedText";
};

export const proofSectionFields: YextFields<ProofSectionProps> = {
  text: {
    type: "entityField",
    label: "Text",
    filter: {
      types: ["type.string"],
    },
  },
  textAlignment: {
    type: "radio",
    label: "Text Alignment",
    options: [
      { label: "Left", value: "left" },
      { label: "Center", value: "center" },
      { label: "Right", value: "right" },
    ],
  },
  // 🎯 UI CONTROL INTERFACE: Exposing your custom keys to the editor sidebar selection menus
  backgroundColorChoice: {
    type: "select",
    label: "Block Background Theme",
    options: [
      { label: "Fitness Primary Red", value: "primary" },
      { label: "Deep Brand Charcoal", value: "dark" },
      { label: "Clean White Canvas", value: "light" },
    ],
  },
  textColorChoice: {
    type: "select",
    label: "Block Typography Tone",
    options: [
      { label: "Deep Charcoal Black", value: "dark" },
      { label: "Clean White Canvas", value: "light" },
      { label: "Standard Slate Body Text", value: "text" },
      { label: "Soft Muted Subheading Gray", value: "mutedText" },
    ],
  },
};

export const ProofSectionComponent: PuckComponent<ProofSectionProps> = (props) => {
  const {text, textAlignment, backgroundColorChoice, textColorChoice} = props;
    const { i18n } = useTranslation();
  const streamDocument = useDocument() as Record<string, any>;
  const resolvedText = resolveComponentData(
    props.text,
    i18n.language,
    streamDocument
  );

  // 📐 Resolving the select keys straight to the singular CSS variables generated by themeResolver
  const bgStyles = `var(--colors-palette-${backgroundColorChoice})`;
  const colorStyles = `var(--colors-palette-${textColorChoice})`;

    return (
    <section className="py-12 px-6 bg-palette-tertiary text-palette-secondary transition-colors duration-200">
    <div className="max-w-4xl mx-auto text-center">
      <h2 className="text-4xl font-headings-fontWeight text-headings-textColor mb-4">
        {resolvedText}
      </h2>
      <p className="text-palette-quaternary opacity-90 mb-6">
        Production ready styling linked perfectly across local and cloud pipelines.
      </p>
    </div>
  </section>
  );
};


export const ProofSection: YextComponentConfig<ProofSectionProps> = {
  label: "Proof Section",
  fields: proofSectionFields,
  defaultProps: {
    text: {
      field: "name",
      constantValue: {
        defaultValue: "Visual Editor bespoke template is working.",
      },
      constantValueEnabled: true,
    },
    textAlignment: "center",
    // 🚀 SEEDING THE FALLBACK DEFAULTS: Ensuring values load cleanly immediately on drop
    backgroundColorChoice: "light",
    textColorChoice: "text"
  },
  render: ProofSectionComponent,
};
